/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupSetupRouteImport } from './routes/setup/_setup'
import { Route as SetupSetupIndexRouteImport } from './routes/setup/_setup.index'
import { Route as AppAppIndexRouteImport } from './routes/app/_app.index'
import { Route as SetupSetupWizardRouteImport } from './routes/setup/_setup.wizard'
import { Route as SetupSetupFileUploadRouteImport } from './routes/setup/_setup.file-upload'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSetupRoute = SetupSetupRouteImport.update({
  id: '/setup/_setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSetupIndexRoute = SetupSetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupSetupRoute,
} as any)
const AppAppIndexRoute = AppAppIndexRouteImport.update({
  id: '/app/_app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupSetupWizardRoute = SetupSetupWizardRouteImport.update({
  id: '/wizard',
  path: '/wizard',
  getParentRoute: () => SetupSetupRoute,
} as any)
const SetupSetupFileUploadRoute = SetupSetupFileUploadRouteImport.update({
  id: '/file-upload',
  path: '/file-upload',
  getParentRoute: () => SetupSetupRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/setup': typeof SetupSetupRouteWithChildren
  '/setup/file-upload': typeof SetupSetupFileUploadRoute
  '/setup/wizard': typeof SetupSetupWizardRoute
  '/app/': typeof AppAppIndexRoute
  '/setup/': typeof SetupSetupIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/setup/file-upload': typeof SetupSetupFileUploadRoute
  '/setup/wizard': typeof SetupSetupWizardRoute
  '/app': typeof AppAppIndexRoute
  '/setup': typeof SetupSetupIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/setup/_setup': typeof SetupSetupRouteWithChildren
  '/setup/_setup/file-upload': typeof SetupSetupFileUploadRoute
  '/setup/_setup/wizard': typeof SetupSetupWizardRoute
  '/app/_app/': typeof AppAppIndexRoute
  '/setup/_setup/': typeof SetupSetupIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/setup'
    | '/setup/file-upload'
    | '/setup/wizard'
    | '/app/'
    | '/setup/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/setup/file-upload' | '/setup/wizard' | '/app' | '/setup'
  id:
    | '__root__'
    | '/'
    | '/setup/_setup'
    | '/setup/_setup/file-upload'
    | '/setup/_setup/wizard'
    | '/app/_app/'
    | '/setup/_setup/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SetupSetupRoute: typeof SetupSetupRouteWithChildren
  AppAppIndexRoute: typeof AppAppIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/_setup': {
      id: '/setup/_setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/_setup/': {
      id: '/setup/_setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupSetupIndexRouteImport
      parentRoute: typeof SetupSetupRoute
    }
    '/app/_app/': {
      id: '/app/_app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppAppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/_setup/wizard': {
      id: '/setup/_setup/wizard'
      path: '/wizard'
      fullPath: '/setup/wizard'
      preLoaderRoute: typeof SetupSetupWizardRouteImport
      parentRoute: typeof SetupSetupRoute
    }
    '/setup/_setup/file-upload': {
      id: '/setup/_setup/file-upload'
      path: '/file-upload'
      fullPath: '/setup/file-upload'
      preLoaderRoute: typeof SetupSetupFileUploadRouteImport
      parentRoute: typeof SetupSetupRoute
    }
  }
}

interface SetupSetupRouteChildren {
  SetupSetupFileUploadRoute: typeof SetupSetupFileUploadRoute
  SetupSetupWizardRoute: typeof SetupSetupWizardRoute
  SetupSetupIndexRoute: typeof SetupSetupIndexRoute
}

const SetupSetupRouteChildren: SetupSetupRouteChildren = {
  SetupSetupFileUploadRoute: SetupSetupFileUploadRoute,
  SetupSetupWizardRoute: SetupSetupWizardRoute,
  SetupSetupIndexRoute: SetupSetupIndexRoute,
}

const SetupSetupRouteWithChildren = SetupSetupRoute._addFileChildren(
  SetupSetupRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SetupSetupRoute: SetupSetupRouteWithChildren,
  AppAppIndexRoute: AppAppIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
